version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - docker build -t hello:latest .
      - docker tag hello 117432927484.dkr.ecr.eu-central-1.amazonaws.com/test-dev
  post_build:
    commands:
      - docker push 117432927484.dkr.ecr.eu-central-1.amazonaws.com/test-dev
      - printf '[{"name":Dev-Application-Testing,"imageUri":"%s"}]' 117432927484.dkr.ecr.eu-central-1.amazonaws.com/test-dev > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
